### ISSUE TITLE
[Bug Report] when you add #USERNAME in front of the URL it looks like you logged into that account

### ISSUE THREAD

**Issue by PoIygon** [CodeGuy92/CodeGuy92.github.io#10]
**Describe the bug**
Basically I got bored and I think I saw a link with #USERNAME in front of it. Then I tried it and it looks like I logged into that account.

**Screenshots**
If you have any screenshots, please list them here.

**Device info**
My browser / operating system: IPad iOS 14.6, ChromeiOS 90.0.4430.216, No Flash version detected

**Comment by CodeGuy92** [comment]
duplicate of #10

**Comment by CodeGuy92** [comment]
i mean #8
