### ISSUE TITLE
[Feature Request] Scratch Account System

### ISSUE THREAD

**Issue by CodeGuy92** [CodeGuy92/CodeGuy92.github.io#3]
**Describe the feature you'd like**
I am working on an account system for the website, using my own authentication plugin™

**List all of the benefits that this feature will give us**
Nothing, just a nice addition to the website... maybe banning users?

**List all of the bad stuff that this feature will give us**
Nothing... really

**Comment by CodeGuy92** [comment]
The system now works, but i am giving it an error status so that only i can test it.

**Comment by CodeGuy92** [comment]
### Current instructions to log in are:
1. Go to the [account verification page](https://lankybox01.leahcimto.com/account/verify.html).
2. Go to the [verification project](https://scratch.mit.edu/projects/524136137/) & enter the code.
3. Press the "done" button on the account verification page.
4. Done.

**Comment by CodeGuy92** [comment]
Here's the code i used for fetching the data.
```fetch(`https://clouddata.scratch.mit.edu/logs?projectid=${524136137}&offset=0&limit=40`)
.then(res => res.json())
.then(res => {
 // do anything with res[0]
})```

**Comment by CodeGuy92** [comment]
Currently, this is what happens when you try logging in with the new system. [(image)](https://user-images.githubusercontent.com/79767244/116813632-4867c300-ab5d-11eb-8de5-2bba0b1ccc9c.PNG)
I am trying to add support for modal boxes so i do not have to use alerts.

**Comment by markverb1** [comment]
> Currently, this is what happens when you try logging in with the new system. [(image)](https://user-images.githubusercontent.com/79767244/116813632-4867c300-ab5d-11eb-8de5-2bba0b1ccc9c.PNG)
> I am trying to add support for modal boxes so i do not have to use alerts.

markdown images exist

**Comment by CodeGuy92** [comment]
what

**Comment by CodeGuy92** [comment]
Ik, but it was taking up too much space

**Comment by markverb1** [comment]
Oh ok.

На чт, 6 май 2021 г., 19:57 LankyBox01 ***@***.***> написа:

**Comment by CodeGuy92** [comment]
could u at least help me with my repo

**Comment by markverb1** [comment]
Sure, if you can tell me what you need help with.

На чт, 6 май 2021 г., 20:05 LankyBox01 ***@***.***> написа:

**Comment by CodeGuy92** [comment]
creating a cookie token system since currently you can forge anyone's account by modifying cookies

**Comment by markverb1** [comment]
> creating a cookie token system since currently you can forge anyone's account by modifying cookies

Hm... I haven't done anything like this before so might not be able to help.

**Comment by CodeGuy92** [comment]
e

**Comment by markverb1** [comment]
> e

also why are you not using ajax or fetch

**Comment by CodeGuy92** [comment]
cuz i do not know how they work or how to implement tjem on my site. I am new to js
