### ISSUE TITLE
Banned.

### ISSUE THREAD

**Issue by CodeGuy92** [CodeGuy92/CodeGuy92.github.io#3]
Bruh i've been banned from my own site
![1](https://user-images.githubusercontent.com/79767244/114421037-8bb5be00-9bbd-11eb-848a-067eb5a1eff3.PNG)

**Comment by CodeGuy92** [comment]
And with the new cookie update, i literally cannot visit any part of the site. LOL!

**Comment by leahcimto** [comment]
lol was this automatic or something

**Comment by leahcimto** [comment]
lol the issue is here: https://github.com/CodeGuy92/CodeGuy92.github.io/blob/0f444ebf7a1a14f776e057f14a5facdd635d152b/assets/ban-check.js#L6

**Comment by CodeGuy92** [comment]
I know.

I don't know how to code in js, tough. Why are there 2 equal signs!? Also why is the statement in brackets??? What is a statement??!??!?!?!

**Comment by leahcimto** [comment]
the two equal signs are there because i believe username = lankybox01 would set username to lankybox01 when you really just want to check if it is (don't quote me on that though because all i know is that's how it works in python)

**Comment by leahcimto** [comment]
also how did you make this if you don't know js

**Comment by CodeGuy92** [comment]
I know it was just a joke. But the way i set cookies up made it so that my ban expires in 2022

**Comment by CodeGuy92** [comment]
OOF

**Comment by CodeGuy92** [comment]
> also how did you make this if you don't know js

Do you want me to ban you?

**Comment by leahcimto** [comment]
> > also how did you make this if you don't know js
> 
> Do you want me to ban you?

huh i never said that where did you get that from???????/?/

**Comment by leahcimto** [comment]
also pls ban me

**Comment by CodeGuy92** [comment]
Now try entering your username. You would literally not be able to visit the website anymore

**Comment by leahcimto** [comment]
haha blocked cookie

**Comment by CodeGuy92** [comment]
haha blocked ip

**Comment by CodeGuy92** [comment]
JK

**Comment by leahcimto** [comment]
lol

**Comment by CodeGuy92** [comment]
This is a huge ssecurity risk tough

**Comment by leahcimto** [comment]
look at #6
